# Generated by Django 5.2.6 on 2025-11-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vwheartratetoday_alter_vwdailysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account was deleted', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when account is soft deleted'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_is_acti_8ee55c_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['deleted_at'], name='usuarios_deleted_49dcca_idx'),
        ),
    ]
