# Generated by Django 5.2.6 on 2025-11-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_deleted_at_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidor',
            name='is_simulating',
            field=models.BooleanField(default=False, help_text='If True, synthetic data will be generated for this user'),
        ),
    ]
